### ISSUE TITLE
Не работает 

### ISSUE THREAD

**Issue by LazarenkoA** [Lead-Tools/tirex#15]
Шаблон `[\d]{3,}`, текст "авмваим4334мммммс" и пишет что нет вхождений. Такой шаблон тож не подходит `[\d]+`, да что уж там и такой тоже `[\d]`
Вот граф:
``` json
[
	{},
	{
		"8": 2,
		"0": 2,
		"1": 2,
		"2": 2,
		"3": 2,
		"4": 2,
		"5": 2,
		"6": 2,
		"7": 2,
		"9": 2,
		"pos": 1
	},
	{
		"{": 3
	},
	{
		"3": 4
	},
	{
		",": 5
	},
	{
		"}": 6
	},
	{
		"end": true
	}
]
```

**Comment by tsukanov-as** [comment]
Не могу сейчас проверить. Нет 1С под рукой. Но емнип оно работает именно как матчер всей строки. Т.е. буквы в начале строки оно само не пропустит. Т.е. надо что-то типа `\w*[\d]+` (а вообще не понял зачем тут квадратные скобки (набор), вроде так проще `\w*\d+`)
Это если речь про Match(). Примеры можно в тестах посмотреть

**Comment by LazarenkoA** [comment]
>Т.е. надо что-то типа \w*[\d]+

ясно, но тем не менее спецификация регулярок мой вариант поддерживает, а твоя реализация нет
